name: Terraform CI

on:
  push:
    branches:
      - main  # or your target branch
  pull_request:
    branches:
      - main  # or your target branch

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Set your desired version

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan (only to preview changes)
      - name: Terraform Plan
        run: terraform plan
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

      # Optional Step 5: Apply (remove this step if you only want to plan)
      # Uncomment this section if you want Terraform to apply changes automatically after a plan
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

